export const COVER_LETTER_RESUME_MAX_CHARS = 18_000;
export const COVER_LETTER_VACANCY_MAX_CHARS = 18_000;
export const COVER_LETTER_ADAPTATION_MAX_CHARS = 12_000;
export const COVER_LETTER_MAX_TOKENS = 1_800;
